//! Event system for cursor-proxy
//!
//! Provides an async broadcast channel for proxy events.
//! Events flow from the proxy core to subscribers like the dashboard,
//! IPC clients, and capture modules.

use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;
use std::collections::HashMap;

/// Channel capacity for event broadcasts
const BROADCAST_CAPACITY: usize = 1024;

/// Events generated by the proxy
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProxyEvent {
    /// New connection opened
    ConnectionOpened {
        connection_id: u64,
        peer_addr: String,
    },

    /// Connection closed
    ConnectionClosed {
        connection_id: u64,
    },

    /// Request started (before forwarding to upstream)
    RequestStarted {
        request_id: u64,
        connection_id: u64,
        method: String,
        path: String,
        endpoint: String,
        headers: HashMap<String, String>,
    },

    /// Request completed successfully
    RequestCompleted {
        request_id: u64,
        status: u16,
        duration_ms: u64,
        request_size: usize,
        response_size: Option<usize>,
    },

    /// Request failed
    RequestFailed {
        request_id: u64,
        error: String,
        duration_ms: u64,
    },

    /// Upstream connection pool event
    UpstreamConnection {
        host: String,
        action: UpstreamAction,
        pool_size: usize,
    },

    /// Capture saved to disk
    CaptureSaved {
        request_id: u64,
        path: String,
        size: usize,
    },

    /// Agent activity detected (AI assistant behavior)
    AgentActivity {
        activity: AgentActivityType,
        tool_name: Option<String>,
        metadata: Option<HashMap<String, String>>,
    },

    /// Injection applied to request/response
    InjectionApplied {
        request_id: u64,
        injection_type: String,
        details: String,
    },

    /// Proxy started
    ProxyStarted {
        port: u16,
        capture_enabled: bool,
        injection_enabled: bool,
    },

    /// Proxy stopped
    ProxyStopped {
        reason: String,
    },

    /// Configuration changed
    ConfigChanged {
        key: String,
        value: String,
    },
}

/// Upstream connection pool actions
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum UpstreamAction {
    /// New connection established
    Connected,
    /// Existing connection reused
    Reused,
    /// Connection disconnected
    Disconnected,
    /// Connection failed
    Failed { is_tls: bool },
}

/// Agent activity types for monitoring AI assistant behavior
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum AgentActivityType {
    /// Agent is generating a response
    Thinking,
    /// Tool call started
    ToolCallStarted,
    /// Tool call completed
    ToolCallCompleted,
    /// Agent is waiting for user input
    WaitingForUser,
    /// Code generation in progress
    CodeGeneration,
}

/// Service categories for traffic classification
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ServiceCategory {
    /// Chat/conversation endpoints
    Chat,
    /// AI model endpoints
    Ai,
    /// Queue/background job endpoints
    Queue,
    /// Telemetry/analytics endpoints
    Telemetry,
    /// System/infrastructure endpoints
    System,
    /// Unclassified
    Unknown,
}

impl ServiceCategory {
    /// Classify a request path into a service category
    pub fn from_path(path: &str) -> Self {
        let path_lower = path.to_lowercase();

        if path_lower.contains("chat") || path_lower.contains("unified") || path_lower.contains("conversation") {
            ServiceCategory::Chat
        } else if path_lower.contains("ai") || path_lower.contains("model") || path_lower.contains("complete") {
            ServiceCategory::Ai
        } else if path_lower.contains("queue") || path_lower.contains("job") || path_lower.contains("task") {
            ServiceCategory::Queue
        } else if path_lower.contains("telemetry") || path_lower.contains("analytics") || path_lower.contains("metrics") {
            ServiceCategory::Telemetry
        } else if path_lower.contains("health") || path_lower.contains("status") || path_lower.contains("config") {
            ServiceCategory::System
        } else {
            ServiceCategory::Unknown
        }
    }

    /// Get display name for the category
    pub fn name(&self) -> &'static str {
        match self {
            ServiceCategory::Chat => "Chat",
            ServiceCategory::Ai => "AI",
            ServiceCategory::Queue => "Queue",
            ServiceCategory::Telemetry => "Telemetry",
            ServiceCategory::System => "System",
            ServiceCategory::Unknown => "Unknown",
        }
    }

    /// Get ANSI color code for the category
    pub fn color(&self) -> &'static str {
        match self {
            ServiceCategory::Chat => "\x1b[35m",      // Magenta
            ServiceCategory::Ai => "\x1b[36m",        // Cyan
            ServiceCategory::Queue => "\x1b[34m",     // Blue
            ServiceCategory::Telemetry => "\x1b[33m", // Yellow
            ServiceCategory::System => "\x1b[32m",    // Green
            ServiceCategory::Unknown => "\x1b[37m",   // White
        }
    }
}

/// Parse endpoint name from path
pub fn parse_path(path: &str) -> String {
    // Extract the endpoint name from paths like:
    // /aiserver.v1.AiService/StreamChat -> StreamChat
    // /api/v1/chat -> chat
    
    if let Some(last_slash) = path.rfind('/') {
        path[last_slash + 1..].to_string()
    } else {
        path.to_string()
    }
}

/// Event broadcaster - the sender side of the event channel
pub struct EventBroadcaster {
    sender: broadcast::Sender<ProxyEvent>,
}

impl EventBroadcaster {
    /// Create a new broadcaster
    pub fn new() -> Self {
        let (sender, _) = broadcast::channel(BROADCAST_CAPACITY);
        Self { sender }
    }

    /// Send an event to all subscribers
    pub fn send(&self, event: ProxyEvent) {
        // Ignore errors (no subscribers is fine)
        let _ = self.sender.send(event);
    }

    /// Get a new receiver for subscribing to events
    pub fn subscribe(&self) -> EventReceiver {
        EventReceiver {
            receiver: self.sender.subscribe(),
        }
    }

    /// Get current number of subscribers
    pub fn subscriber_count(&self) -> usize {
        self.sender.receiver_count()
    }
}

impl Default for EventBroadcaster {
    fn default() -> Self {
        Self::new()
    }
}

impl Clone for EventBroadcaster {
    fn clone(&self) -> Self {
        Self {
            sender: self.sender.clone(),
        }
    }
}

/// Event receiver - the subscriber side of the event channel
pub struct EventReceiver {
    receiver: broadcast::Receiver<ProxyEvent>,
}

impl EventReceiver {
    /// Receive the next event (async)
    pub async fn recv(&mut self) -> Option<ProxyEvent> {
        loop {
            match self.receiver.recv().await {
                Ok(event) => return Some(event),
                Err(broadcast::error::RecvError::Closed) => return None,
                Err(broadcast::error::RecvError::Lagged(_)) => {
                    // Subscriber fell behind, skip missed events and try again
                    continue;
                }
            }
        }
    }

    /// Try to receive without blocking
    pub fn try_recv(&mut self) -> Option<ProxyEvent> {
        match self.receiver.try_recv() {
            Ok(event) => Some(event),
            Err(_) => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_service_category_from_path() {
        assert_eq!(ServiceCategory::from_path("/aiserver.v1.AiService/StreamChat"), ServiceCategory::Chat);
        assert_eq!(ServiceCategory::from_path("/api/v1/telemetry"), ServiceCategory::Telemetry);
        assert_eq!(ServiceCategory::from_path("/unknown/path"), ServiceCategory::Unknown);
    }

    #[test]
    fn test_parse_path() {
        assert_eq!(parse_path("/aiserver.v1.AiService/StreamChat"), "StreamChat");
        assert_eq!(parse_path("/api/v1/chat"), "chat");
        assert_eq!(parse_path("simple"), "simple");
    }

    #[tokio::test]
    async fn test_event_broadcast() {
        let broadcaster = EventBroadcaster::new();
        let mut receiver = broadcaster.subscribe();

        broadcaster.send(ProxyEvent::ProxyStarted {
            port: 8443,
            capture_enabled: true,
            injection_enabled: false,
        });

        let event = receiver.recv().await;
        assert!(matches!(event, Some(ProxyEvent::ProxyStarted { port: 8443, .. })));
    }
}
